#! /usr/bin/env python

print 'loading modules'

import numpy, halfspace

print 'generating data'

fault = halfspace.OkadaSource(
  strike=160, dip=35, rake=105, slip=1,
  ztop=-2e3, zbottom=-10e3, length=20e3,
  xtrace=0, ytrace=0 )

Y, X = numpy.meshgrid(
  numpy.linspace( -25e3, 25e3, 50 ),
  numpy.linspace( -25e3, 25e3, 50 ) )

XYZ = numpy.array([ X, Y, numpy.zeros_like(X) ]).T

disp = fault.displacement( XYZ, poisson=.25 )

print disp
