#! /usr/bin/env python

from __future__ import print_function
import numpy, halfspace

delta = 1e-6

source = halfspace.okada( strike=355, dip=83,
                          strikeslip=2, dipslip=.3,
                          zbottom=-17e3, ztop=-1e3, length=20e3,
                          xtrace=0, ytrace=0 )

print( 'Source:', source )

x, y = 2, 3

print()
print( 'SURFACE POINT (%s,%s,0)' % ( x, y ) )
print()

print( 'displacement:' )
print( source.displacement( [x,y,0], poisson=.25 ) )

print( 'gradient:' )
grad = source.gradient( [x,y,0], poisson=.25 )
print( grad )

print( 'relative error:' )
dudx = ( source.displacement( [x+delta,y,0], poisson=.25 ) - source.displacement( [x-delta,y,0], poisson=.25 ) ) / (2*delta)
dudy = ( source.displacement( [x,y+delta,0], poisson=.25 ) - source.displacement( [x,y-delta,0], poisson=.25 ) ) / (2*delta)
dudz = ( source.displacement( [x,y,0], poisson=.25 ) - source.displacement( [x,y,-delta], poisson=.25 ) ) / delta
print( numpy.array( [ dudx, dudy, dudz ] ) / grad - numpy.ones(( 3, 3 )) )

print( 'strain:' )
print( source.strain( [x,y,9], poisson=.25 ) )

print( 'stress:' )
print( source.stress( [x,y,0], poisson=.25, young=80.75e9 ) )

x, y, z = 2, 3, -1

print()
print( 'INTERNAL POINT (%s,%s,%s)' % ( x, y, z ) )
print()

print( 'displacement:' )
print( source.displacement( [x,y,z], poisson=.25 ) )

print( 'gradient:' )
grad = source.gradient( [x,y,z], poisson=.25 )
print( grad )

print( 'relative error:' )
dudx = ( source.displacement( [x+delta,y,z], poisson=.25 ) - source.displacement( [x-delta,y,z], poisson=.25 ) ) / (2*delta)
dudy = ( source.displacement( [x,y+delta,z], poisson=.25 ) - source.displacement( [x,y-delta,z], poisson=.25 ) ) / (2*delta)
dudz = ( source.displacement( [x,y,z+delta], poisson=.25 ) - source.displacement( [x,y,z-delta], poisson=.25 ) ) / (2*delta)
print( numpy.array( [ dudx, dudy, dudz ] ) / grad - numpy.ones(( 3, 3 )) )

print( 'strain:' )
print( source.strain( [x,y,z], poisson=.25 ) )

print( 'stress:' )
print( source.stress( [x,y,z], poisson=.25, young=80.75e9 ) )
